[package]
name = "txcv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt", "macros", "io-std"] }
governor = "0.6"
keyring = "2"
colored = "2"
serde = { version = "1", features = ["derive"] }
tencentcloud = { git = "https://github.com/Sherlock-Holo/tencentcloud.git" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
requestty = "0.5"
